apiVersion: apps/v1
kind: Deployment
metadata:
  name: signal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signal
  template:
    metadata:
      labels:
        app: signal
    spec:
      containers:
        - name: signal
          image: alinazariii/ds-signal:0.1.0
          envFrom:
            - configMapRef:
                name: signal
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: signal
data:
  KAFKA_HOSTS: "kafka-controller-0.kafka-controller-headless:9092,kafka-controller-1.kafka-controller-headless:9092,kafka-controller-2.kafka-controller-headless:9092"