apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion
          image: alinazariii/ds-ingestion:0.2.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ingestion
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion
spec:
  selector:
    app: ingestion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ingestion
data:
  KAFKA_HOSTS: "kafka-controller-0.kafka-controller-headless:9092,kafka-controller-1.kafka-controller-headless:9092,kafka-controller-2.kafka-controller-headless:9092"